# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      # setup msbuild
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      # setup nuget
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
        
      # restore nuget packages
      - name: restore nuget packages
        run: nuget restore "Audio Spectrum.sln"
        
      # build
      - name: build
        run: msbuild "PSpectrum v2\\PSpectrum v2.csproj" /p:Configuration=Release /p:GeneratePackageOnBuild=false
        
      # push to powercord plugin
      - name: push to powercord plugin
        run: |
          git config --global user.email "malte.linke.ml@gmai.com"
          git config --global user.name "parzival-space"
          git clone https://parzival-space:${{ secrets.API_TOKEN_GITHUB }}@github.com/parzival-space/powercord-pspectrum.git target
          cp ".\PSpectrum v2\bin\Release\PSpectrum.exe" .\target\bin\PSpectrum.exe
          cd target
          git add .
          git diff-index --quiet HEAD || git commit -m "Automated update of PSpectrum.exe"
          git push https://parzival-space:${{ secrets.API_TOKEN_GITHUB }}@github.com/parzival-space/powercord-pspectrum.git
          cd ..
          Remove-Item -Recurse -Force .\target
      
      # create new release of PSpectrum.exe
      #- name: Upload binaries to release
      #  uses: svenstaro/upload-release-action@v2
      #  with:
      #    repo_token: ${{ secrets.API_TOKEN_GITHUB }}
      #    file: "PSpectrum v2\\bin\\Release\\PSpectrum.exe"
      #    asset_name: PSpectrum.exe
      #    tag: Release
      #    prerelease: false
      #    overwrite: true
